rollback;

CREATE TABLE  product (
  PRODUCT_ID NUMBER(20)  NOT NULL,
  PRODUCT_CODE NVARCHAR2(20) NOT NULL,
  PRODUCT_DESC NVARCHAR2(255) NOT NULL
);

ALTER TABLE PRODUCT 
ADD (
  CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID ));

CREATE SEQUENCE PRODUCT_seq;

CREATE OR REPLACE TRIGGER PRODUCT_bir 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW

BEGIN
  SELECT PRODUCT_seq.NEXTVAL
  INTO   :new.PRODUCT_id
  FROM   dual;
END;



CREATE TABLE  product_qoh (
  QOH_ID NUMBER(20)  NOT NULL ,
  PRODUCT_ID NUMBER(20)  NOT NULL,
  QTY NUMBER(10)  NOT NULL
);

ALTER TABLE PRODUCT_QOH
ADD (
  CONSTRAINT QOH_ID_PK PRIMARY KEY (QOH_ID ));

CREATE SEQUENCE PRODUCT_QOH_seq;

CREATE OR REPLACE TRIGGER PRODUCT_QOH_bir 
BEFORE INSERT ON PRODUCT_QOH 
FOR EACH ROW

BEGIN
  SELECT PRODUCT_QOH_seq.NEXTVAL
  INTO   :new.QOH_ID
  FROM   dual;
END;


ALTER TABLE PRODUCT_QOH
ADD CONSTRAINT fk_product
  FOREIGN KEY (PRODUCT_ID)
  REFERENCES PRODUCT(PRODUCT_ID);
